version: '3.8'

services:
  postgres:
    image: postgres
    container_name: hibernate_intro
    environment:
      POSTGRES_DB: hibernate_intro_db
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
